package edu.stanford.protege.robot.command.materialize;

/**
 * Boolean flags for ROBOT materialize command.
 *
 * <p>
 * These flags control various aspects of the materialization behavior, including redundant axiom
 * removal, new ontology creation, and inference annotation.
 *
 * @see <a href="https://robot.obolibrary.org/materialize">ROBOT Materialize Documentation</a>
 */
public enum MaterializeFlags {

    /**
     * Enable removal of redundant subclass axioms after materialization.
     *
     * <p>
     * Generates {@code --remove-redundant-subclass-axioms true}. When specified, subclass axioms
     * that are entailed by other axioms in the ontology are removed.
     */
    REMOVE_REDUNDANT_SUBCLASS_AXIOMS("--remove-redundant-subclass-axioms"),

    /**
     * Create a new ontology containing only the materialized axioms.
     *
     * <p>
     * Generates {@code --create-new-ontology true}. When specified, a new ontology is created with
     * only the inferred axioms rather than adding them to the existing ontology.
     */
    CREATE_NEW_ONTOLOGY("--create-new-ontology"),

    /**
     * Annotate inferred axioms with provenance information.
     *
     * <p>
     * Generates {@code --annotate-inferred-axioms true}. When specified, each inferred axiom is
     * annotated to indicate it was generated by the reasoner.
     */
    ANNOTATE_INFERRED_AXIOMS("--annotate-inferred-axioms"),
    ;

    private final String flagName;

    MaterializeFlags(String flagName) {
        this.flagName = flagName;
    }

    /**
     * Returns the ROBOT CLI flag.
     *
     * @return the flag string (e.g., {@code "--remove-redundant-subclass-axioms"})
     */
    public String getFlagName() {
        return flagName;
    }
}
